In [12]:
import pandas as pd

In [13]:
data = [
    ['张海','男',18],
    ['李霞','女',20],
    ['王君','女',25],
]
df = pd.DataFrame(data=data,columns=('姓名','性别','年龄'))
df

   姓名 性别  年龄
0  张海  男  18
1  李霞  女  20
2  王君  女  25

In [14]:
df['姓名']

0    张海
1    李霞
2    王君
Name: 姓名, dtype: object

In [15]:
df[['姓名','性别']]

   姓名 性别
0  张海  男
1  李霞  女
2  王君  女

In [16]:
df.loc[[0,1],'性别']

0    男
1    女
Name: 性别, dtype: object

In [17]:
df.loc[[0,1],['姓名','性别']]

   姓名 性别
0  张海  男
1  李霞  女

In [18]:
df.iloc[:2,:2]

   姓名 性别
0  张海  男
1  李霞  女

In [19]:
df[df['年龄']>18]

   姓名 性别  年龄
1  李霞  女  20
2  王君  女  25

In [20]:
df.loc[df['年龄']>18,['性别','年龄']]

  性别  年龄
1  女  20
2  女  25

In [21]:
df.loc[df['性别']=='男','性别'] = 1
df

   姓名 性别  年龄
0  张海  1  18
1  李霞  女  20
2  王君  女  25

In [22]:
df.loc[df['性别']=='女','性别'] = 0
df

   姓名 性别  年龄
0  张海  1  18
1  李霞  0  20
2  王君  0  25